import { SelectOption } from '@/components/ui/Select';

export const dutchMunicipalities: SelectOption[] = [
  { value: 'Aa en Hunze', label: 'Aa en Hunze' },
  { value: 'Aalsmeer', label: 'Aalsmeer' },
  { value: 'Aalten', label: 'Aalten' },
  { value: 'Achtkarspelen', label: 'Achtkarspelen' },
  { value: 'Alblasserdam', label: 'Alblasserdam' },
  { value: 'Albrandswaard', label: 'Albrandswaard' },
  { value: 'Alkmaar', label: 'Alkmaar' },
  { value: 'Almelo', label: 'Almelo' },
  { value: 'Almere', label: 'Almere' },
  { value: 'Alphen aan den Rijn', label: 'Alphen aan den Rijn' },
  { value: 'Alphen-Chaam', label: 'Alphen-Chaam' },
  { value: 'Altena', label: 'Altena' },
  { value: 'Ameland', label: 'Ameland' },
  { value: 'Amersfoort', label: 'Amersfoort' },
  { value: 'Amstelveen', label: 'Amstelveen' },
  { value: 'Amsterdam', label: 'Amsterdam' },
  { value: 'Apeldoorn', label: 'Apeldoorn' },
  { value: 'Arnhem', label: 'Arnhem' },
  { value: 'Assen', label: 'Assen' },
  { value: 'Asten', label: 'Asten' },
  { value: 'Baarle-Nassau', label: 'Baarle-Nassau' },
  { value: 'Baarn', label: 'Baarn' },
  { value: 'Barendrecht', label: 'Barendrecht' },
  { value: 'Barneveld', label: 'Barneveld' },
  { value: 'Beek (L.)', label: 'Beek (L.)' },
  { value: 'Beekdaelen', label: 'Beekdaelen' },
  { value: 'Beesel', label: 'Beesel' },
  { value: 'Berg en Dal', label: 'Berg en Dal' },
  { value: 'Bergeijk', label: 'Bergeijk' },
  { value: 'Bergen (L.)', label: 'Bergen (L.)' },
  { value: 'Bergen (NH.)', label: 'Bergen (NH.)' },
  { value: 'Bergen op Zoom', label: 'Bergen op Zoom' },
  { value: 'Berkelland', label: 'Berkelland' },
  { value: 'Bernheze', label: 'Bernheze' },
  { value: 'Best', label: 'Best' },
  { value: 'Beuningen', label: 'Beuningen' },
  { value: 'Beverwijk', label: 'Beverwijk' },
  { value: 'De Bilt', label: 'De Bilt' },
  { value: 'Bladel', label: 'Bladel' },
  { value: 'Blaricum', label: 'Blaricum' },
  { value: 'Bloemendaal', label: 'Bloemendaal' },
  { value: 'Bodegraven-Reeuwijk', label: 'Bodegraven-Reeuwijk' },
  { value: 'Boekel', label: 'Boekel' },
  { value: 'Borger-Odoorn', label: 'Borger-Odoorn' },
  { value: 'Borne', label: 'Borne' },
  { value: 'Borsele', label: 'Borsele' },
  { value: 'Boxtel', label: 'Boxtel' },
  { value: 'Breda', label: 'Breda' },
  { value: 'Bronckhorst', label: 'Bronckhorst' },
  { value: 'Brummen', label: 'Brummen' },
  { value: 'Brunssum', label: 'Brunssum' },
  { value: 'Bunnik', label: 'Bunnik' },
  { value: 'Bunschoten', label: 'Bunschoten' },
  { value: 'Buren', label: 'Buren' },
  { value: 'Capelle aan den IJssel', label: 'Capelle aan den IJssel' },
  { value: 'Castricum', label: 'Castricum' },
  { value: 'Coevorden', label: 'Coevorden' },
  { value: 'Cranendonck', label: 'Cranendonck' },
  { value: 'Culemborg', label: 'Culemborg' },
  { value: 'Dalfsen', label: 'Dalfsen' },
  { value: 'Dantumadiel', label: 'Dantumadiel' },
  { value: 'Delft', label: 'Delft' },
  { value: 'Deurne', label: 'Deurne' },
  { value: 'Deventer', label: 'Deventer' },
  { value: 'Diemen', label: 'Diemen' },
  { value: 'Dijk en Waard', label: 'Dijk en Waard' },
  { value: 'Dinkelland', label: 'Dinkelland' },
  { value: 'Doesburg', label: 'Doesburg' },
  { value: 'Doetinchem', label: 'Doetinchem' },
  { value: 'Dongen', label: 'Dongen' },
  { value: 'Dordrecht', label: 'Dordrecht' },
  { value: 'Drechterland', label: 'Drechterland' },
  { value: 'Drimmelen', label: 'Drimmelen' },
  { value: 'Dronten', label: 'Dronten' },
  { value: 'Druten', label: 'Druten' },
  { value: 'Duiven', label: 'Duiven' },
  { value: 'Echt-Susteren', label: 'Echt-Susteren' },
  { value: 'Edam-Volendam', label: 'Edam-Volendam' },
  { value: 'Ede', label: 'Ede' },
  { value: 'Eemnes', label: 'Eemnes' },
  { value: 'Eemsdelta', label: 'Eemsdelta' },
  { value: 'Eersel', label: 'Eersel' },
  { value: 'Eijsden-Margraten', label: 'Eijsden-Margraten' },
  { value: 'Eindhoven', label: 'Eindhoven' },
  { value: 'Elburg', label: 'Elburg' },
  { value: 'Emmen', label: 'Emmen' },
  { value: 'Enkhuizen', label: 'Enkhuizen' },
  { value: 'Enschede', label: 'Enschede' },
  { value: 'Epe', label: 'Epe' },
  { value: 'Ermelo', label: 'Ermelo' },
  { value: 'Etten-Leur', label: 'Etten-Leur' },
  { value: 'De Fryske Marren', label: 'De Fryske Marren' },
  { value: 'Geertruidenberg', label: 'Geertruidenberg' },
  { value: 'Geldrop-Mierlo', label: 'Geldrop-Mierlo' },
  { value: 'Gemert-Bakel', label: 'Gemert-Bakel' },
  { value: 'Gennep', label: 'Gennep' },
  { value: 'Gilze en Rijen', label: 'Gilze en Rijen' },
  { value: 'Goeree-Overflakkee', label: 'Goeree-Overflakkee' },
  { value: 'Goes', label: 'Goes' },
  { value: 'Goirle', label: 'Goirle' },
  { value: 'Gooise Meren', label: 'Gooise Meren' },
  { value: 'Gorinchem', label: 'Gorinchem' },
  { value: 'Gouda', label: 'Gouda' },
  { value: "'s-Gravenhage", label: "'s-Gravenhage" },
  { value: 'Groningen', label: 'Groningen' },
  { value: 'Gulpen-Wittem', label: 'Gulpen-Wittem' },
  { value: 'Haaksbergen', label: 'Haaksbergen' },
  { value: 'Haarlem', label: 'Haarlem' },
  { value: 'Haarlemmermeer', label: 'Haarlemmermeer' },
  { value: 'Halderberge', label: 'Halderberge' },
  { value: 'Hardenberg', label: 'Hardenberg' },
  { value: 'Harderwijk', label: 'Harderwijk' },
  { value: 'Hardinxveld-Giessendam', label: 'Hardinxveld-Giessendam' },
  { value: 'Harlingen', label: 'Harlingen' },
  { value: 'Hattem', label: 'Hattem' },
  { value: 'Heemskerk', label: 'Heemskerk' },
  { value: 'Heemstede', label: 'Heemstede' },
  { value: 'Heerde', label: 'Heerde' },
  { value: 'Heerenveen', label: 'Heerenveen' },
  { value: 'Heerlen', label: 'Heerlen' },
  { value: 'Heeze-Leende', label: 'Heeze-Leende' },
  { value: 'Heiloo', label: 'Heiloo' },
  { value: 'Den Helder', label: 'Den Helder' },
  { value: 'Hellendoorn', label: 'Hellendoorn' },
  { value: 'Helmond', label: 'Helmond' },
  { value: 'Hendrik-Ido-Ambacht', label: 'Hendrik-Ido-Ambacht' },
  { value: 'Hengelo (O.)', label: 'Hengelo (O.)' },
  { value: "'s-Hertogenbosch", label: "'s-Hertogenbosch" },
  { value: 'Heumen', label: 'Heumen' },
  { value: 'Heusden', label: 'Heusden' },
  { value: 'Hillegom', label: 'Hillegom' },
  { value: 'Hilvarenbeek', label: 'Hilvarenbeek' },
  { value: 'Hilversum', label: 'Hilversum' },
  { value: 'Hoeksche Waard', label: 'Hoeksche Waard' },
  { value: 'Hof van Twente', label: 'Hof van Twente' },
  { value: 'Het Hogeland', label: 'Het Hogeland' },
  { value: 'Hollands Kroon', label: 'Hollands Kroon' },
  { value: 'Hoogeveen', label: 'Hoogeveen' },
  { value: 'Hoorn', label: 'Hoorn' },
  { value: 'Horst aan de Maas', label: 'Horst aan de Maas' },
  { value: 'Houten', label: 'Houten' },
  { value: 'Huizen', label: 'Huizen' },
  { value: 'Hulst', label: 'Hulst' },
  { value: 'IJsselstein', label: 'IJsselstein' },
  { value: 'Kaag en Braassem', label: 'Kaag en Braassem' },
  { value: 'Kampen', label: 'Kampen' },
  { value: 'Kapelle', label: 'Kapelle' },
  { value: 'Katwijk', label: 'Katwijk' },
  { value: 'Kerkrade', label: 'Kerkrade' },
  { value: 'Koggenland', label: 'Koggenland' },
  { value: 'Krimpen aan den IJssel', label: 'Krimpen aan den IJssel' },
  { value: 'Krimpenerwaard', label: 'Krimpenerwaard' },
  { value: 'Laarbeek', label: 'Laarbeek' },
  { value: 'Land van Cuijk', label: 'Land van Cuijk' },
  { value: 'Landgraaf', label: 'Landgraaf' },
  { value: 'Landsmeer', label: 'Landsmeer' },
  { value: 'Lansingerland', label: 'Lansingerland' },
  { value: 'Laren (NH.)', label: 'Laren (NH.)' },
  { value: 'Leeuwarden', label: 'Leeuwarden' },
  { value: 'Leiden', label: 'Leiden' },
  { value: 'Leiderdorp', label: 'Leiderdorp' },
  { value: 'Leidschendam-Voorburg', label: 'Leidschendam-Voorburg' },
  { value: 'Lelystad', label: 'Lelystad' },
  { value: 'Leudal', label: 'Leudal' },
  { value: 'Leusden', label: 'Leusden' },
  { value: 'Lingewaard', label: 'Lingewaard' },
  { value: 'Lisse', label: 'Lisse' },
  { value: 'Lochem', label: 'Lochem' },
  { value: 'Loon op Zand', label: 'Loon op Zand' },
  { value: 'Lopik', label: 'Lopik' },
  { value: 'Losser', label: 'Losser' },
  { value: 'Maasdriel', label: 'Maasdriel' },
  { value: 'Maasgouw', label: 'Maasgouw' },
  { value: 'Maashorst', label: 'Maashorst' },
  { value: 'Maassluis', label: 'Maassluis' },
  { value: 'Maastricht', label: 'Maastricht' },
  { value: 'Medemblik', label: 'Medemblik' },
  { value: 'Meerssen', label: 'Meerssen' },
  { value: 'Meierijstad', label: 'Meierijstad' },
  { value: 'Meppel', label: 'Meppel' },
  { value: 'Middelburg (Z.)', label: 'Middelburg (Z.)' },
  { value: 'Midden-Delfland', label: 'Midden-Delfland' },
  { value: 'Midden-Drenthe', label: 'Midden-Drenthe' },
  { value: 'Midden-Groningen', label: 'Midden-Groningen' },
  { value: 'Moerdijk', label: 'Moerdijk' },
  { value: 'Molenlanden', label: 'Molenlanden' },
  { value: 'Montferland', label: 'Montferland' },
  { value: 'Montfoort', label: 'Montfoort' },
  { value: 'Mook en Middelaar', label: 'Mook en Middelaar' },
  { value: 'Neder-Betuwe', label: 'Neder-Betuwe' },
  { value: 'Nederweert', label: 'Nederweert' },
  { value: 'Nieuwegein', label: 'Nieuwegein' },
  { value: 'Nieuwkoop', label: 'Nieuwkoop' },
  { value: 'Nijkerk', label: 'Nijkerk' },
  { value: 'Nijmegen', label: 'Nijmegen' },
  { value: 'Nissewaard', label: 'Nissewaard' },
  { value: 'Noardeast-Fryslân', label: 'Noardeast-Fryslân' },
  { value: 'Noord-Beveland', label: 'Noord-Beveland' },
  { value: 'Noordenveld', label: 'Noordenveld' },
  { value: 'Noordoostpolder', label: 'Noordoostpolder' },
  { value: 'Noordwijk', label: 'Noordwijk' },
  { value: 'Nuenen, Gerwen en Nederwetten', label: 'Nuenen, Gerwen en Nederwetten' },
  { value: 'Nunspeet', label: 'Nunspeet' },
  { value: 'Oegstgeest', label: 'Oegstgeest' },
  { value: 'Oirschot', label: 'Oirschot' },
  { value: 'Oisterwijk', label: 'Oisterwijk' },
  { value: 'Oldambt', label: 'Oldambt' },
  { value: 'Oldebroek', label: 'Oldebroek' },
  { value: 'Oldenzaal', label: 'Oldenzaal' },
  { value: 'Olst-Wijhe', label: 'Olst-Wijhe' },
  { value: 'Ommen', label: 'Ommen' },
  { value: 'Oost Gelre', label: 'Oost Gelre' },
  { value: 'Oosterhout', label: 'Oosterhout' },
  { value: 'Ooststellingwerf', label: 'Ooststellingwerf' },
  { value: 'Oostzaan', label: 'Oostzaan' },
  { value: 'Opmeer', label: 'Opmeer' },
  { value: 'Opsterland', label: 'Opsterland' },
  { value: 'Oss', label: 'Oss' },
  { value: 'Oude IJsselstreek', label: 'Oude IJsselstreek' },
  { value: 'Ouder-Amstel', label: 'Ouder-Amstel' },
  { value: 'Oudewater', label: 'Oudewater' },
  { value: 'Overbetuwe', label: 'Overbetuwe' },
  { value: 'Papendrecht', label: 'Papendrecht' },
  { value: 'Peel en Maas', label: 'Peel en Maas' },
  { value: 'Pekela', label: 'Pekela' },
  { value: 'Pijnacker-Nootdorp', label: 'Pijnacker-Nootdorp' },
  { value: 'Purmerend', label: 'Purmerend' },
  { value: 'Putten', label: 'Putten' },
  { value: 'Raalte', label: 'Raalte' },
  { value: 'Reimerswaal', label: 'Reimerswaal' },
  { value: 'Renkum', label: 'Renkum' },
  { value: 'Renswoude', label: 'Renswoude' },
  { value: 'Reusel-De Mierden', label: 'Reusel-De Mierden' },
  { value: 'Rheden', label: 'Rheden' },
  { value: 'Rhenen', label: 'Rhenen' },
  { value: 'Ridderkerk', label: 'Ridderkerk' },
  { value: 'Rijssen-Holten', label: 'Rijssen-Holten' },
  { value: 'Rijswijk (ZH.)', label: 'Rijswijk (ZH.)' },
  { value: 'Roerdalen', label: 'Roerdalen' },
  { value: 'Roermond', label: 'Roermond' },
  { value: 'De Ronde Venen', label: 'De Ronde Venen' },
  { value: 'Roosendaal', label: 'Roosendaal' },
  { value: 'Rotterdam', label: 'Rotterdam' },
  { value: 'Rozendaal', label: 'Rozendaal' },
  { value: 'Rucphen', label: 'Rucphen' },
  { value: 'Schagen', label: 'Schagen' },
  { value: 'Scherpenzeel', label: 'Scherpenzeel' },
  { value: 'Schiedam', label: 'Schiedam' },
  { value: 'Schiermonnikoog', label: 'Schiermonnikoog' },
  { value: 'Schouwen-Duiveland', label: 'Schouwen-Duiveland' },
  { value: 'Simpelveld', label: 'Simpelveld' },
  { value: 'Sint-Michielsgestel', label: 'Sint-Michielsgestel' },
  { value: 'Sittard-Geleen', label: 'Sittard-Geleen' },
  { value: 'Sliedrecht', label: 'Sliedrecht' },
  { value: 'Sluis', label: 'Sluis' },
  { value: 'Smallingerland', label: 'Smallingerland' },
  { value: 'Soest', label: 'Soest' },
  { value: 'Someren', label: 'Someren' },
  { value: 'Son en Breugel', label: 'Son en Breugel' },
  { value: 'Stadskanaal', label: 'Stadskanaal' },
  { value: 'Staphorst', label: 'Staphorst' },
  { value: 'Stede Broec', label: 'Stede Broec' },
  { value: 'Steenbergen', label: 'Steenbergen' },
  { value: 'Steenwijkerland', label: 'Steenwijkerland' },
  { value: 'Stein (L.)', label: 'Stein (L.)' },
  { value: 'Stichtse Vecht', label: 'Stichtse Vecht' },
  { value: 'Súdwest-Fryslân', label: 'Súdwest-Fryslân' },
  { value: 'Terneuzen', label: 'Terneuzen' },
  { value: 'Terschelling', label: 'Terschelling' },
  { value: 'Texel', label: 'Texel' },
  { value: 'Teylingen', label: 'Teylingen' },
  { value: 'Tholen', label: 'Tholen' },
  { value: 'Tiel', label: 'Tiel' },
  { value: 'Tilburg', label: 'Tilburg' },
  { value: 'Tubbergen', label: 'Tubbergen' },
  { value: 'Twenterand', label: 'Twenterand' },
  { value: 'Tynaarlo', label: 'Tynaarlo' },
  { value: 'Tytsjerksteradiel', label: 'Tytsjerksteradiel' },
  { value: 'Uitgeest', label: 'Uitgeest' },
  { value: 'Uithoorn', label: 'Uithoorn' },
  { value: 'Urk', label: 'Urk' },
  { value: 'Utrecht', label: 'Utrecht' },
  { value: 'Utrechtse Heuvelrug', label: 'Utrechtse Heuvelrug' },
  { value: 'Vaals', label: 'Vaals' },
  { value: 'Valkenburg aan de Geul', label: 'Valkenburg aan de Geul' },
  { value: 'Valkenswaard', label: 'Valkenswaard' },
  { value: 'Veendam', label: 'Veendam' },
  { value: 'Veenendaal', label: 'Veenendaal' },
  { value: 'Veere', label: 'Veere' },
  { value: 'Veldhoven', label: 'Veldhoven' },
  { value: 'Velsen', label: 'Velsen' },
  { value: 'Venlo', label: 'Venlo' },
  { value: 'Venray', label: 'Venray' },
  { value: 'Vijfheerenlanden', label: 'Vijfheerenlanden' },
  { value: 'Vlaardingen', label: 'Vlaardingen' },
  { value: 'Vlieland', label: 'Vlieland' },
  { value: 'Vlissingen', label: 'Vlissingen' },
  { value: 'Voerendaal', label: 'Voerendaal' },
  { value: 'Voorne aan Zee', label: 'Voorne aan Zee' },
  { value: 'Voorschoten', label: 'Voorschoten' },
  { value: 'Voorst', label: 'Voorst' },
  { value: 'Vught', label: 'Vught' },
  { value: 'Waadhoeke', label: 'Waadhoeke' },
  { value: 'Waalre', label: 'Waalre' },
  { value: 'Waalwijk', label: 'Waalwijk' },
  { value: 'Waddinxveen', label: 'Waddinxveen' },
  { value: 'Wageningen', label: 'Wageningen' },
  { value: 'Wassenaar', label: 'Wassenaar' },
  { value: 'Waterland', label: 'Waterland' },
  { value: 'Weert', label: 'Weert' },
  { value: 'West Betuwe', label: 'West Betuwe' },
  { value: 'West Maas en Waal', label: 'West Maas en Waal' },
  { value: 'Westerkwartier', label: 'Westerkwartier' },
  { value: 'Westerveld', label: 'Westerveld' },
  { value: 'Westervoort', label: 'Westervoort' },
  { value: 'Westerwolde', label: 'Westerwolde' },
  { value: 'Westland', label: 'Westland' },
  { value: 'Weststellingwerf', label: 'Weststellingwerf' },
  { value: 'Wierden', label: 'Wierden' },
  { value: 'Wijchen', label: 'Wijchen' },
  { value: 'Wijdemeren', label: 'Wijdemeren' },
  { value: 'Wijk bij Duurstede', label: 'Wijk bij Duurstede' },
  { value: 'Winterswijk', label: 'Winterswijk' },
  { value: 'Woensdrecht', label: 'Woensdrecht' },
  { value: 'Woerden', label: 'Woerden' },
  { value: 'De Wolden', label: 'De Wolden' },
  { value: 'Wormerland', label: 'Wormerland' },
  { value: 'Woudenberg', label: 'Woudenberg' },
  { value: 'Zaanstad', label: 'Zaanstad' },
  { value: 'Zaltbommel', label: 'Zaltbommel' },
  { value: 'Zandvoort', label: 'Zandvoort' },
  { value: 'Zeewolde', label: 'Zeewolde' },
  { value: 'Zeist', label: 'Zeist' },
  { value: 'Zevenaar', label: 'Zevenaar' },
  { value: 'Zoetermeer', label: 'Zoetermeer' },
  { value: 'Zoeterwoude', label: 'Zoeterwoude' },
  { value: 'Zuidplas', label: 'Zuidplas' },
  { value: 'Zundert', label: 'Zundert' },
  { value: 'Zutphen', label: 'Zutphen' },
  { value: 'Zwartewaterland', label: 'Zwartewaterland' },
  { value: 'Zwijndrecht', label: 'Zwijndrecht' },
  { value: 'Zwolle', label: 'Zwolle' },
];
